// File __EUNIT_TestControl_Test_Lab2_BF609_Core0.cpp generated by E-UNIT program
// Author: ibietela.whyte1
// Date: Tue 2019/10/15 at 02:34:29 PM

#define HUMAN_INTERVENTION_TEST_LEVEL 20
#define ALL_TEST_LEVELS 0xFFFF

void AutomatedTestLevelControl(void)
{
    return;
}
