// File __EUNIT_TestControl_BF5333_TDD_CoreTimer_Library.cpp generated by E-UNIT program
// Author: Ibietela Whyte
// Date: Tue 2019/11/19 at 06:09:47 PM

#define HUMAN_INTERVENTION_TEST_LEVEL 20
#define ALL_TEST_LEVELS 0xFFFF

void AutomatedTestLevelControl(void)
{
    return;
}
